# docker-compose-production.yml
version: "3"
services:
  app-flask:
    build: ./app    
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - lista-de-compras-letsencrypt

  lista-de-compras-letsencrypt:
    image: linuxserver/letsencrypt
    container_name: lista-de-compras-letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/letsencrypt:/config
    environment:
      - EMAIL=mikelet@gmail.com
      - URL=api.asgardev.ga
        # - SUBDOMAINS=www
      - VALIDATION=http
      - TZ=America/Sao_Paulo
      - PUID=1001
      - PGID=1001
